### ISSUE TITLE
Concat parser?

### ISSUE THREAD

**Issue by ch3pjw** [javawizard/parcon#11]
I'm rather new to writing parsers, so perhaps I'm abusing `parcon`, but I found myself writing 
`Translate(<some_parser>, concat)[<type>]` an aweful lot. I got around some of the verbosity by defining `Concat = lambda p: Tranlate(p, concat)`, which cleaned up my code a lot. Is it worth defining a `Concat` centrally, or is this redefinition so trivial as to not bother hardcore parser authors?

**Comment by javawizard** [comment]
So `x[y]` is just shorthand for `Translate(x, y)`, so you should just be able to do `<some_parser>[concat][<type>]`. That'd be the same number of characters as `Concat(<some_parser>)[<type>]`. Would that work?

**Comment by javawizard** [comment]
(And you're certainly not abusing parcon - this exact pattern tends to surface quite frequently when parsing e.g. runs of digits to turn them into integers.)

**Comment by ch3pjw** [comment]
\<lightbulb/\> Aha! Ok, that makes far more sense, thanks!
